### ISSUE TITLE
Onie integration issue for custom board.

### ISSUE THREAD

**Issue by ankitkumarsr** [opencomputeproject/onie#1005]
For my custom-board i am able to get onie installation option attached in (Onie-image2.png)
![image](https://user-images.githubusercontent.com/64590976/178135145-ba2a98a6-d01b-4cf1-a43c-89b70f9182a4.png)

if booted manually , the following expected menu is not coming
![image](https://user-images.githubusercontent.com/64590976/178135163-125290e5-510d-4d84-acb5-ace071a76b64.png)

Please provide suggestion What is missing here to get desired output.

**Comment by ehdoyle** [comment]
Duplicate of [https://github.com/opencomputeproject/onie/issues/1000](https://github.com/opencomputeproject/onie/issues/1000)
