### ISSUE TITLE
Missing tar file | parted-3.1.tar.xz

### ISSUE THREAD

**Issue by tchandramohan** [opencomputeproject/onie#1015]
Hi Alex,

The build for ONIE for a KVM target was successful. However when I run a distclean and try to build ONIE & Demo NOS together for a KVM target, the build fails at one point. In particular, the build says it is unable to find the file -> parted-**3.1**.tar.xz in the directory src/onie/build/download

However, in the same directory src/onie/build/download, I find the file 'parted-**3.4**.tar.xz'
I am attaching screenshots for both. 
Please tell me how to proceed. Is this a bug? 

![image](https://user-images.githubusercontent.com/114584567/196441813-92a681e6-9d5f-4a81-bdb9-c56b81df9511.png)
![image](https://user-images.githubusercontent.com/114584567/196441963-9bb7eb1b-fd6a-47c8-9b40-d24b5d1db855.png)

**Comment by ehdoyle** [comment]
Hi - had you also building the ARM virtual target? I recall that the ARM and x86 virtual builds used two different versions of one package and building one after the other in the same build area would fail. (IIRC upgrading them both to the latest version was a dependency cascade nightmare that wasn't worth the cost of addressing at the time.)
If that is the case I'm surprised a distclean didn't take care of that. Emptying out the ./build area should fix that, or you may be able to selectively delete the offending downloaded parted tar.xz file and a 'make all' should redownload it.

**Comment by tchandramohan** [comment]
It looks like an ARM target image was in place under the build/images directory. 
I did a distclean and emptied the build area like you suggested. 
I have ONIE installer files and demo NOS files created under onie/build/images
![image](https://user-images.githubusercontent.com/114584567/196482755-52071a05-afa1-472e-88d0-0249f8cf1cf5.png)

Question: Currently, I am following this readme for ONIE installation [https://github.com/opencomputeproject/onie/blob/master/machine/kvm_x86_64/INSTALL#L72]
However this readme does not highlight how to install demo NOS since the installer is a .bin file. 

Previously, I was able to successfully install ONIE (for a KVM target) using this setup
![image](https://user-images.githubusercontent.com/114584567/196483541-b6d652bc-4878-4810-8374-c976d6fb9594.png)
And I was also able to boot from hard disk after instalation.

How do I get demo NOS in after installing ONIE?

**Comment by ehdoyle** [comment]
Once ONIE is embedded on the hard drive, it should default to running a waterfall discovery process to find images to install, and while there are a lot of places one could put the image to be found,  I usually copy the demo os bin file to be under a web server, then for onie:
onie-stop  -- to stop the discovery process
onie-nos-install  --URL to the demo OS image.
...at which point it should install, reboot, and come up in the demo os.
