### ISSUE TITLE
To prevent user from accidentally typing damaging commands during ONIE updating itself

### ISSUE THREAD

**Issue by david56** [opencomputeproject/onie#102]
A test case of issuing 'reboot' command during ONIE updating itself was reported recently.  It's obvious that u-boot firmware lost and the machine never booted up.  Some enhancements will be done in the future.

> The case of the user accidentally typing some damaging command, of
> which several commands exist that could cause problems during upgrade,
> is interesting.  What would be the right thing here?
> 
> I can imagine doing something:
> - during upgrade disable stdin on all terminals.
> - during upgrade go into single user mode.
> 
> Or something like that.  Of course you are also faced with undoing
> these operations if the upgrade fails and the user wants to poke
> around some more.

Please look up the thread for details:
http://lists.opencompute.org/pipermail/opencompute-onie/2014-December/000315.html

**Comment by cbrune** [comment]
Closing as old
