### ISSUE TITLE
ONIE build env should support archive.debian.org

### ISSUE THREAD

**Issue by nrf53** [opencomputeproject/onie#1051]
Due to following change, Dockerfile should be changed.
https://lists.debian.org/debian-devel-announce/2023/03/msg00006.html

Add below before apt-get commands.
```# Modify Debian Repo
RUN sed -i 's/deb.debian.org/archive.debian.org/g' /etc/apt/sources.list && \
    sed -i 's/security.debian.org/archive.debian.org/g' /etc/apt/sources.list && \
    sed -i '/stretch-updates/d' /etc/apt/sources.list

```
https://github.com/opencomputeproject/onie/blob/master/contrib/build-env/Dockerfile

**Comment by ehdoyle** [comment]
Could you provide an example of the platform where this is impacting build, and what the failure is?
Also, DUE addressed a Debian 9 archive change a while back, so the latest version may solve your problem.
[https://github.com/CumulusNetworks/DUE/blob/master/image-patches/debian/9/filesystem/etc/apt/patch-sources.list](https://github.com/CumulusNetworks/DUE/blob/master/image-patches/debian/9/filesystem/etc/apt/patch-sources.list)
