### ISSUE TITLE
Testing: test case 12 (DHCP Inexact - TFTP Bootfile) doesn't discover the bootfile

### ISSUE THREAD

**Issue by cobracmder** [opencomputeproject/onie#127]
Using ```./test-onie.py -I eth1 -i 192.168.1.100/24 -m 7072cfaa34fa -t 12 -o onie_installer demo-installer-powerpc-accton_as4600_54t-r0.bin``` results in ONIE not finding the image.

Similar to #126

**Comment by cobracmder** [comment]
Pcap file: http://1drv.ms/1AxGq1D

Based on pcap file, this is either a bug in the device or ONIE.  Will know more when another device is tested.

**Comment by cbrune** [comment]
Indeed, this is the same as #126 

Please try patch in PR #130

**Comment by cbrune** [comment]
fixed by 327ecca
