### ISSUE TITLE
Testing: test cases that use <vendor> incorrectly use vendor_id vs vendor name

### ISSUE THREAD

**Issue by cobracmder** [opencomputeproject/onie#129]
```test-onie.py``` expects a numeric value for onie_vendor (in this case, 259), however when test-onie generates the name for the installer file, it inserts this value into the name. Therefore, we end up with a file named ```onie/contrib/autobuild/output/test-13/www-root/onie-installer-powerpc-259_accton_as4600_54t-r0```, which is not found by ONIE in discovery mode

**Comment by cbrune** [comment]
closed by 702c194 and 396d4b8
