### ISSUE TITLE
apply-patch-series: stg: command not found

### ISSUE THREAD

**Issue by gcooper** [opencomputeproject/onie#197]
I have cloned the git to run the ONIE for quanta_ly2. After the command ($ make -j4 MACHINEROOT=../machine/quanta/ MACHINE=quanta_ly2 all ), i notice while its compiling that i get two errors.
this error happens when running the patch for u-boot and kernel-patch 
 error:
build-config/scripts/apply-patch-series: line 22: stg: command not found 

I dont know if these errors are crucial or not but after compiling, there are no binaries in the images folders. 

I also tried the alternate root and running the build.sh and i have the same errors. my version of ubuntu is 3.13.0-24-generic. 

![capture](https://cloud.githubusercontent.com/assets/12625340/7834546/49c00bb2-043e-11e5-80ae-dd87c44af346.PNG)

![capture2](https://cloud.githubusercontent.com/assets/12625340/7834549/4fb96658-043e-11e5-8b43-ca8132413db4.PNG)

**Comment by cbrune** [comment]
Looks like you have not properly prepared your build host.  Please read this:
https://github.com/opencomputeproject/onie/wiki/Building-ONIE#preparing-a-new-build-machine

You need to install the stgit package on your build host.
