### ISSUE TITLE
Update wiki for image discovery waterfall: persistent directory #233

### ISSUE THREAD

**Issue by cobracmder** [opencomputeproject/onie#234]
Update wiki for image discovery waterfall: persistent directory.  This relates to PR #233

**Comment by cbrune** [comment]
Updated the wiki about the new image discovery method:
https://github.com/opencomputeproject/onie/wiki/Design-Spec-SW-Updating-ONIE

Updated the wiki about the new firmware management CLI, `onie-fwpkg`:
https://github.com/opencomputeproject/onie/wiki/CLI-Reference#onie-fwpkg
