### ISSUE TITLE
50_onie_grub does not generate correct config

### ISSUE THREAD

**Issue by lakesh-sharma** [opencomputeproject/onie#249]
50_onie_grub should be invoked by NOS installer.
-it would re-generate the onie's grub config.
-And it would provide onie's chainload menu entry, along with any available
  diags entry config to NOS grub config.

At present, it seems that 50_onie_grub would not generate correct config entries.
It would miss some of config params listed in machine config.
More on this issue has been discussed in thread, and possible solutions high-lighted.

http://lists.opencompute.org/pipermail/opencompute-onie/2015-August/000826.html

**Comment by cbrune** [comment]
See patch sent to mailing list:

http://lists.opencompute.org/pipermail/opencompute-onie/2015-August/000836.html

**Comment by lakesh-sharma** [comment]
the patch looks good.
grub-extra.cfg would be generated by build infra ?

**Comment by cbrune** [comment]
yes.  grub-extra.cfg is generated by build-config/scripts/onie-mk-installer.sh during final image creation.

**Comment by paavaanan** [comment]
is there any workaround available for this bug?
