### ISSUE TITLE
OCE: If IP entered in non-CIDR format DHCP configuration incorrect

### ISSUE THREAD

**Issue by mrhpearson** [opencomputeproject/onie#269]
When using OCE if the "-i" option is used and the IP address is not entered in CIDR format the subnet configuration for the dhcp is incorrect.
Consider adding checking to OCE to confirm IP address is in CIDR format

**Comment by cobracmder** [comment]
Pushed patch to master: https://github.com/opencomputeproject/onie/commit/122466b9f6e8bb86962f144edc1be9cd31e5636e
