### ISSUE TITLE
patches: busybox: ip neigh feature

### ISSUE THREAD

**Issue by bittorf** [opencomputeproject/onie#276]
i like your "ip neigh" patch. thank you!

1)
Have you considered to send it upstream?

2)
I tweaked it, that it compiles with OpenWrt.
Can we use it in the OpenWrt project, means: can i submit your work as a patch to the OpenWrt-Mailinglist? (the licence fits)

**Comment by cbrune** [comment]
re: 1) We should upstream that patch.  Looking into it.

re: 2) sure, of course

**Comment by bittorf** [comment]
thanks, i can see your patch on the busybox-ML - thank you!
