### ISSUE TITLE
x86 onie - GRUB menu rendering/ risc of accidental break / ONL erase

### ISSUE THREAD

**Issue by ongrid** [opencomputeproject/onie#320]
Hi Team. Just a field operation notes on bootup process of x86 systems via GRUB:
1. switches have no VGA adaptor so the installation/maintenance personnel can observe bootup process via dumb RS-232 terminal emulators (HyperTerminal/Putty/minicom/screen/kermit) or some kind of terminal server. By the fact, among all available tools, only kermit renders GRUB menu correctly - other tools push some badly structured data to the output. This makes the switch absolutely unmanageable, especially by low-skilled field staff or by current terminal servers used by company.
2. It's possible to accidentally break normal bootup process just by DownArrow-keystroke and, being in not well-rendered menu, it's diffucult to understand what happens. The best practical thing that personnel can do - just to power-cycle the switch. The worst - to press enter on "blindly-selected" option. This option can be catastrophic - "ONL uninstall". We should have some safety measure - some kind of confirmation on selected non-default item. Moreover Down-arrow symbol can be pushed into terminal by always-connected terminal device (for example, on initialization on bootup in case of entire-rack power-cut). We should use more rare sequence for normal bootup break - Ctrl-C, Ctrl-Break or some other combination. Not arrow-down + Enter.

**Comment by cbrune** [comment]
closing as cf6e91c ("NOS mode: a persistent NOS mode boot option") fixed a number of usability problems.
