### ISSUE TITLE
Static IPv4 address allocation fallback scheme

### ISSUE THREAD

**Issue by cbrune** [opencomputeproject/onie#333]
The fallback static IPv4 address scheme is outdated and causing problems.

This thoroughly described here:

http://lists.opencompute.org/pipermail/opencompute-onie/2016-February/001026.html

Close this bug after the patch, documentation and OCE tests are updated.

**Comment by capveg** [comment]
Patch for the code submitted here: https://github.com/opencomputeproject/onie/pull/334

**Comment by cbrune** [comment]
Commit 23fdae8 addresses the implementation.
The wiki documentation has also been updated.
Leaving this open to track the OCE changes.

**Comment by cobracmder** [comment]
Reviewed OCE with ONIE images before and after this change, everything is kosher.
