### ISSUE TITLE
Issue installing NOS image

### ISSUE THREAD

**Issue by suriya92** [opencomputeproject/onie#338]
Hi,

I'm new to ONIE. I would like to install an image which I have built. I'm using my local Apache http server to fetch the image, but I keep getting some random errors like this :

:*\* Installer Mode Enabled **
ONIE:/ #
ONIE:/ # install_url http://168.127.181.242/onie-installer.bin..
Stopping: discover... done.
Info: Fetching http://168.127.181.242/onie-installer.bin ...
Connecting to 168.127.181.242 (168.127.181.242:80)
installer            100% |******************************_|  6073k  0:00:00 ETA
ONIE: Executing installer: http://168.127.181.242/onie-installer.bin
/installer: line 2: ▒▒▒: not found
▒x▒^▒▒z▒^▒x▒^: not found^▒▒▒▒^▒닆0H▒▒▒!Á▒}▒▒▒@▒
▒@: not foundine 2:
/installer: line 2: ▒▒▒: not found
/installer: line 2: can't open ▒K▒Ѭfu▒n_}k▒▒▒▒R: no such file
/installer: line 2: ▒▒▒▒z▒5VlkK: not found
▒В^▒▒▒▒{x▒▒▒▒▒: not found
/installer: line 2: ▒▒@u
▒M▒: not found▒H!▒H▒▒}H▒▒H
/installer: line 9: syntax error: unexpected ")"

I tried both the bzI and vmlinux.bin image. And when  I tried to install a precompiled Ubuntu image which  I downloaded from ubuntu page, I get this : 

ONIE:/ # install_url http://168.127.181.242/onie-installer.deb2..
Stopping: discover... done.
Info: Fetching http://168.127.181.242/onie-installer.deb ...
Connecting to 168.127.181.242 (168.127.181.242:80)
installer            100% |*******************************| 39486k  0:00:00 ETA
ONIE: Executing installer: http://168.127.181.242/onie-installer.deb
/installer: line 1: syntax error: unexpected newline

Can somebody help me on this? I have been spending several days to figure this out !

**Comment by hanasu** [comment]
What is contained within your image? For example here's the output of a successful install on the Quanta LB9:

```
Package contains:
OS version lb9-r-1.4.12.00.img
Kernel version lb9-kernel-1.0.5.0.img
VM Tracer version vm-.img
```

**Comment by suriya92** [comment]
The image is for a Linux kernel 4.4.3 which I have downloaded from kernel.org and built to get  bzi & vmlinux.bin. I also tried with a precompiled Ubuntu image (3.5.0-23-generic) for which I got the second error.

**Comment by audihsu-qci** [comment]
http://opennetlinux.org/binaries
This is linux built for ONIE.

**Comment by cbrune** [comment]
It looks like ONIE is working fine here, but there is a problem with the installer image you are using.

You should also ask this question on the ONL mailing list.

**Comment by suriya92** [comment]
Thank you. I will reach out to them. But I was thinking any stable linux kernel image would work with ONIE.

**Comment by cbrune** [comment]
The kernel is not the problem.  The problem lies in how the NOS installer is being built.  The installer image being used in this case does not look like an ONIE compatible installer.

**Comment by suriya92** [comment]
Ah.Now I get it.And it seems like the precompiled ONL binaries doesn't support my platform( X86_64-redwood). Do you know how I can build a linux image this is ONIE-compatible?

**Comment by cbrune** [comment]
The demonstration NOS that ships with ONIE is a good example:

https://github.com/opencomputeproject/onie/wiki/Demo-OS

**Comment by suriya92** [comment]
Thank you so much !  I'll try that

**Comment by suriya92** [comment]
And is there a way to enter the bootloader on a white box switch before onie grub menu pops up.  I would like to install a linux image through USB  on the switch.

**Comment by suriya92** [comment]
Can anyone tell me how I can load an ubuntu/debian .iso /.bin image downloaded from internet through ONIE? It throws errors when I try to do so. Or do you have the ONIE-demo OS .bin image?

**Comment by cbrune** [comment]
This describes how to convert a Debian ISO into an ONIE compatible installer:

https://github.com/opencomputeproject/onie/tree/master/contrib/debian-iso

Ubuntu or another distro would be similar, but not identical.

**Comment by suriya92** [comment]
Thanks you ! I will try that

**Comment by suriya92** [comment]
I tried that and i get : 
Verifying image checksum ... OK.
Preparing image archive ... OK
Loading new kernel ...
/tmp/tmp.igZQsv/installer/install.sh: line 18: kexec: not found.

Pls help me with your ideas..

**Comment by cbrune** [comment]
Hmmm.  What version of ONIE are you running?  kexec should be available.

**Comment by suriya92** [comment]
Version   : HEAD-201508120053-dirty
Is there a way to install kexec manually in ONIE?

**Comment by suriya92** [comment]
Additionally, ONIE_config_version=1
onie_kernel_version=3.2.35

**Comment by cbrune** [comment]
closing as inactive for over a year
