### ISSUE TITLE
ONIE install Debian in kvm_x86_64 error

### ISSUE THREAD

**Issue by lockless** [opencomputeproject/onie#664]
When installing debian in a kvm_x86_64, the following error occurs

  +---------------------+ Detecting network hardware +----------------------+
  |　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　 |
  |　　　　　　　　　　0%　 　　　　　　　　　　　　　　　　　　　　|
  |　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　 |
  | Detecting hardware, please wait... 　　　　　　　　　　　　　　　　　|
  |   　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　|
  +--------------------------------------------------------------------------------+

then waiting，but never continue...

Can I get some advice?

**Comment by cbrune** [comment]
Hello @lockless -

A few questions.

- How did you launch the Debian installer from?  Can you share the screen output?
- What hypervisor are you using?

**Comment by lockless** [comment]
Hi, thank you for your answer.
 The follow is the screen output:

ONIE:/ # onie-nos-install http://192.168.12.1/debian-jessie-amd64-mini-ONIE.bin
discover: Rescue mode detected. No discover stopped.
Info: Attempting http://192.168.12.1/debian-jessie-amd64-mini-ONIE.bin ...
Connecting to 192.168.12.1 (192.168.12.1:80)
installer            100% |*******************************| 17871k  0:00:00 ETA
ONIE: Executing installer: http://192.168.12.1/debian-jessie-amd64-mini-ONIE.bin
Verifying image checksum ... OK.
Preparing image archive ... OK.
Loading new kernel ...
my_load:667: do
kexec_core: Starting new kernel
[    0.000000] Initializing cgroup subsys cpuset
[    0.000000] Initializing cgroup subsys cpu
[    0.000000] Initializing cgroup subsys cpuacct
[    0.000000] Linux version 3.16.0-4-amd64 (debian-kernel@lists.debian.org) (gcc version 4.8.4 (Debian 4.8.4-1) ) #1 SMP Debian 3.16.51-2 (2017-12-03)
[    0.000000] Command line: auto=true priority=critical  url=http://192.168.12.1/./debian-preseed.txt --- console=tty0 console=ttyS0,115200n8
[    0.000000] e820: BIOS-provided physical RAM map:
[    0.000000] BIOS-e820: [mem 0x0000000000000100-0x000000000009ffff] usable
[    0.000000] BIOS-e820: [mem 0x0000000000100000-0x000000003ee3bfff] usable
[    0.000000] BIOS-e820: [mem 0x000000003ee3c000-0x000000003ee4dfff] reserved
[    0.000000] BIOS-e820: [mem 0x000000003ee4e000-0x000000003fecdfff] usable
[    0.000000] BIOS-e820: [mem 0x000000003fece000-0x000000003ff25fff] reserved
[    0.000000] BIOS-e820: [mem 0x000000003ff26000-0x000000003ff2dfff] ACPI data
[    0.000000] BIOS-e820: [mem 0x000000003ff2e000-0x000000003ff31fff] ACPI NVS
[    0.000000] BIOS-e820: [mem 0x000000003ff32000-0x000000003ffcffff] usable
[    0.000000] BIOS-e820: [mem 0x000000003ffd0000-0x000000003fffffff] reserved
[    0.000000] NX (Execute Disable) protection: active
[    0.000000] DMI not present or invalid.
[    0.000000] Hypervisor detected: KVM
[    0.000000] AGP: No AGP bridge found
[    0.000000] e820: last_pfn = 0x3ffd0 max_arch_pfn = 0x400000000
[    0.000000] PAT not supported by CPU.
[    0.000000] init_memory_mapping: [mem 0x00000000-0x000fffff]
[    0.000000] init_memory_mapping: [mem 0x3ec00000-0x3edfffff]
[    0.000000] init_memory_mapping: [mem 0x3c000000-0x3ebfffff]
[    0.000000] init_memory_mapping: [mem 0x00100000-0x3bffffff]
[    0.000000] init_memory_mapping: [mem 0x3ee00000-0x3ee3bfff]
[    0.000000] init_memory_mapping: [mem 0x3ee4e000-0x3fecdfff]
[    0.000000] init_memory_mapping: [mem 0x3ff32000-0x3ffcffff]
[    0.000000] RAMDISK: [mem 0x3f05b000-0x3fecdfff]
[    0.000000] ACPI: Early table checksum verification disabled
[    0.000000] ACPI BIOS Error (bug): A valid RSDP was not found (20140424/tbxfroot-212)
[    0.000000] No NUMA configuration found
[    0.000000] Faking a node at [mem 0x0000000000000000-0x000000003ffcffff]
[    0.000000] Initmem setup node 0 [mem 0x00000000-0x3ffcffff]
[    0.000000]   NODE_DATA [mem 0x3ffcb000-0x3ffcffff]
[    0.000000] kvm-clock: Using msrs 4b564d01 and 4b564d00
[    0.000000] kvm-clock: cpu 0, msr 0:3ffc3001, primary cpu clock
[    0.000000] Zone ranges:
[    0.000000]   DMA      [mem 0x00001000-0x00ffffff]
[    0.000000]   DMA32    [mem 0x01000000-0xffffffff]
[    0.000000]   Normal   empty
[    0.000000] Movable zone start for each node
[    0.000000] Early memory node ranges
[    0.000000]   node   0: [mem 0x00001000-0x0009ffff]
[    0.000000]   node   0: [mem 0x00100000-0x3ee3bfff]
[    0.000000]   node   0: [mem 0x3ee4e000-0x3fecdfff]
[    0.000000]   node   0: [mem 0x3ff32000-0x3ffcffff]
[    0.000000] SFI: Simple Firmware Interface v0.81 http://simplefirmware.org
[    0.000000] smpboot: Allowing 1 CPUs, 0 hotplug CPUs
[    0.000000] PM: Registered nosave memory: [mem 0x000a0000-0x000fffff]
[    0.000000] PM: Registered nosave memory: [mem 0x3ee3c000-0x3ee4dfff]
[    0.000000] PM: Registered nosave memory: [mem 0x3fece000-0x3ff25fff]
[    0.000000] PM: Registered nosave memory: [mem 0x3ff26000-0x3ff2dfff]
[    0.000000] PM: Registered nosave memory: [mem 0x3ff2e000-0x3ff31fff]
[    0.000000] e820: [mem 0x40000000-0xffffffff] available for PCI devices
[    0.000000] Booting paravirtualized kernel on KVM
[    0.000000] setup_percpu: NR_CPUS:512 nr_cpumask_bits:512 nr_cpu_ids:1 nr_node_ids:1
[    0.000000] PERCPU: Embedded 27 pages/cpu @ffff88003ec00000 s81664 r8192 d20736 u2097152
[    0.000000] KVM setup async PF for cpu 0
[    0.000000] kvm-stealtime: cpu 0, msr 3ec0d080
[    0.000000] Built 1 zonelists in Node order, mobility grouping on.  Total pages: 258275
[    0.000000] Policy zone: DMA32
[    0.000000] Kernel command line: auto=true priority=critical  url=http://192.168.12.1/./debian-preseed.txt --- console=tty0 console=ttyS0,115200n8
[    0.000000] PID hash table entries: 4096 (order: 3, 32768 bytes)
[    0.000000] AGP: Checking aperture...
[    0.000000] AGP: No AGP bridge found
[    0.000000] Memory: 1006656K/1047524K available (5291K kernel code, 949K rwdata, 1836K rodata, 1208K init, 840K bss, 40868K reserved)
[    0.000000] Hierarchical RCU implementation.
[    0.000000]  RCU dyntick-idle grace-period acceleration is enabled.
[    0.000000]  RCU restricting CPUs from NR_CPUS=512 to nr_cpu_ids=1.
[    0.000000] RCU: Adjusting geometry for rcu_fanout_leaf=16, nr_cpu_ids=1
[    0.000000] NR_IRQS:33024 nr_irqs:256 16
[    0.000000] Console: colour dummy device 80x25
[    0.000000] console [tty0] enabled
[    0.000000] console [ttyS0] enabled
[    0.000000] tsc: Detected 1897.801 MHz processor
[    0.004000] Calibrating delay loop (skipped) preset value.. 3795.60 BogoMIPS (lpj=7591204)
[    0.004000] pid_max: default: 32768 minimum: 301
[    0.004000] Security Framework initialized
[    0.004016] AppArmor: AppArmor disabled by boot time parameter
[    0.005221] Yama: disabled by default; enable with sysctl kernel.yama.*
[    0.006769] Dentry cache hash table entries: 131072 (order: 8, 1048576 bytes)
[    0.008233] Inode-cache hash table entries: 65536 (order: 7, 524288 bytes)
[    0.009849] Mount-cache hash table entries: 2048 (order: 2, 16384 bytes)
[    0.012009] Mountpoint-cache hash table entries: 2048 (order: 2, 16384 bytes)
[    0.013889] Initializing cgroup subsys memory
[    0.014989] Initializing cgroup subsys devices
[    0.016016] Initializing cgroup subsys freezer
[    0.016955] Initializing cgroup subsys net_cls
[    0.017907] Initializing cgroup subsys blkio
[    0.018892] Initializing cgroup subsys perf_event
[    0.020008] Initializing cgroup subsys net_prio
[    0.021080] mce: CPU supports 10 MCE banks
[    0.022119] Last level iTLB entries: 4KB 0, 2MB 0, 4MB 0
[    0.022119] Last level dTLB entries: 4KB 0, 2MB 0, 4MB 0, 1GB 0
[    0.022119] tlb_flushall_shift: 6
[    0.041306] Freeing SMP alternatives memory: 20K (ffffffff81a1d000 - ffffffff81a22000)
[    0.047857] ftrace: allocating 21712 entries in 85 pages
[    0.060034] smpboot: weird, boot CPU (#0) not listed by the BIOS
[    0.061420] smpboot: SMP motherboard not detected
[    0.062511] Enabling x2apic
[    0.063216] Enabled x2apic
[    0.064005] Switched APIC routing to physical x2apic.
[    0.172027] smpboot: SMP disabled
[    0.172782] Performance Events: Broken PMU hardware detected, using software events only.
[    0.174711] Failed to access perfctr msr (MSR c1 is 0)
[    0.177348] x86: Booted up 1 node, 1 CPUs
[    0.178331] smpboot: Total of 1 processors activated (3795.60 BogoMIPS)
[    0.179979] NMI watchdog: disabled (cpu0): hardware events not enabled
[    0.180088] devtmpfs: initialized
[    0.184992] PM: Registering ACPI NVS region [mem 0x3ff2e000-0x3ff31fff] (16384 bytes)
[    0.186964] futex hash table entries: 256 (order: 2, 16384 bytes)
[    0.188972] pinctrl core: initialized pinctrl subsystem
[    0.190293] NET: Registered protocol family 16
[    0.191527] cpuidle: using governor ladder
[    0.192007] cpuidle: using governor menu
[    0.193140] PCI: Using configuration type 1 for base access
[    0.196323] ACPI: Interpreter disabled.
[    0.197346] vgaarb: loaded
[    0.198121] PCI: Probing PCI hardware
[    0.199070] PCI host bridge to bus 0000:00
[    0.200006] pci_bus 0000:00: root bus resource [io  0x0000-0xffff]
[    0.201361] pci_bus 0000:00: root bus resource [mem 0x00000000-0xffffffffff]
[    0.202977] pci_bus 0000:00: No busn resource found for root bus, will use [bus 00-ff]
[    0.218924] pci 0000:00:01.1: legacy IDE quirk: reg 0x10: [io  0x01f0-0x01f7]
[    0.220005] pci 0000:00:01.1: legacy IDE quirk: reg 0x14: [io  0x03f6]
[    0.221552] pci 0000:00:01.1: legacy IDE quirk: reg 0x18: [io  0x0170-0x0177]
[    0.224004] pci 0000:00:01.1: legacy IDE quirk: reg 0x1c: [io  0x0376]
[    0.226093] pci 0000:00:01.3: quirk: [io  0xb000-0xb03f] claimed by PIIX4 ACPI
[    0.228016] pci 0000:00:01.3: quirk: [io  0xb100-0xb10f] claimed by PIIX4 SMB
[    0.260319] vgaarb: setting as boot device: PCI:0000:00:02.0
[    0.261717] vgaarb: device added: PCI:0000:00:02.0,decodes=io+mem,owns=io+mem,locks=none
[    0.317326] amd_nb: Cannot enumerate AMD northbridges
[    0.318650] Switched to clocksource kvm-clock
[    0.323780] pnp: PnP ACPI: disabled
[    0.326369] pci 0000:00:03.0: can't claim BAR 6 [mem 0xfffc0000-0xffffffff pref]: address conflict with 0000:00:02.0 [mem 0xffff0000-0xffffffff pref]
[    0.329515] pci 0000:00:03.0: BAR 6: assigned [mem 0x40000000-0x4003ffff pref]
[    0.331105] NET: Registered protocol family 2
[    0.332538] TCP established hash table entries: 8192 (order: 4, 65536 bytes)
[    0.334158] TCP bind hash table entries: 8192 (order: 5, 131072 bytes)
[    0.335574] TCP: Hash tables configured (established 8192 bind 8192)
[    0.337097] TCP: reno registered
[    0.337907] UDP hash table entries: 512 (order: 2, 16384 bytes)
[    0.339318] UDP-Lite hash table entries: 512 (order: 2, 16384 bytes)
[    0.340870] NET: Registered protocol family 1
[    0.341973] pci 0000:00:00.0: Limiting direct PCI/PCI transfers
[    0.343299] pci 0000:00:01.0: Activating ISA DMA hang workarounds
[    0.344858] Unpacking initramfs...
[    0.687261] Freeing initrd memory: 14796K (ffff88003f05b000 - ffff88003fece000)
[    0.689232] platform rtc_cmos: registered platform RTC device (no PNP device found)
[    0.691223] microcode: CPU0 sig=0x663, pf=0x1, revision=0x1
[    0.692655] microcode: Microcode Update Driver: v2.00 <tigran@aivazian.fsnet.co.uk>, Peter Oruba
[    0.695017] audit: initializing netlink subsys (disabled)
[    0.696385] audit: type=2000 audit(1513306532.940:1): initialized
[    0.698142] HugeTLB registered 2 MB page size, pre-allocated 0 pages
[    0.699682] zbud: loaded
[    0.700517] VFS: Disk quotas dquot_6.5.2
[    0.701519] Dquot-cache hash table entries: 512 (order 0, 4096 bytes)
[    0.703067] msgmni has been set to 1995
[    0.704433] alg: No test for stdrng (krng)
[    0.705461] Block layer SCSI generic (bsg) driver version 0.4 loaded (major 252)
[    0.707077] io scheduler noop registered
[    0.708077] io scheduler deadline registered
[    0.709031] io scheduler cfq registered (default)
[    0.710159] pci_hotplug: PCI Hot Plug PCI Core version: 0.5
[    0.711495] pciehp: PCI Express Hot Plug Controller Driver version: 0.4
[    0.713190] Serial: 8250/16550 driver, 4 ports, IRQ sharing enabled
[    0.745960] serial8250: ttyS0 at I/O 0x3f8 (irq = 4, base_baud = 115200) is a 16550A
[    0.748273] Linux agpgart interface v0.103
[    0.749445] i8042: PNP: No PS/2 controller found. Probing ports directly.
[    0.751848] serio: i8042 KBD port at 0x60,0x64 irq 1
[    0.753071] serio: i8042 AUX port at 0x60,0x64 irq 12
[    0.754388] mousedev: PS/2 mouse device common for all mice
[    0.756131] input: AT Translated Set 2 keyboard as /devices/platform/i8042/serio0/input/input0
[    0.758681] rtc_cmos rtc_cmos: rtc core: registered rtc_cmos as rtc0
[    0.760234] rtc_cmos rtc_cmos: alarms up to one day, 114 bytes nvram
[    0.761692] ledtrig-cpu: registered to indicate activity on CPUs
[    0.763089] AMD IOMMUv2 driver by Joerg Roedel <joerg.roedel@amd.com>
[    0.764602] AMD IOMMUv2 functionality not available on this system
[    0.766089] TCP: cubic registered
[    0.766951] NET: Registered protocol family 10
[    0.768112] mip6: Mobile IPv6
[    0.768855] NET: Registered protocol family 17
[    0.769867] mpls_gso: MPLS GSO support


+---------------------+ Detecting network hardware +----------------------+
|　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　 |
|　　　　　　　　　　0%　 　　　　　　　　　　　　　　　　　　　　|
|　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　 |
| Detecting hardware, please wait... 　　　　　　　　　　　　　　　　　|
| 　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　|
+--------------------------------------------------------------------------------+

to kill kvm:  sudo kill 132817
root@Ubuntu:/home/skunlin/onie-kvm#

**Comment by cbrune** [comment]
Interesting.  I haven't tried this method in 2 years so I gave it a spin just now.

It works for me.  I know that does not help you much.

 I suspect there is something different in our VM configurations or perhaps even QEMU version.  May we can see what is different.

Here is what my console output looks like:
https://gist.github.com/cbrune/b809959115aa8ed8d3b4a053743824e1

I use a very vanilla qemu command line to start the vm.  Like this:
```
sudo qemu-system-x86_64 -enable-kvm -monitor stdio -name curt-onie -m 2048M -smp 2 -vnc 0.0.0.0:244 -vga std -serial telnet:localhost:9005,server -device e1000,netdev=onienet0 -netdev user,id=onienet0,hostfwd=:0.0.0.0:3040-:22,hostfwd=:0.0.0.0:3030-:3030 -drive file=/work/curt/trees/onie-cbrune/build/images/onie-recovery-x86_64-kvm_x86_64-r0.iso,media=cdrom -drive file=../onie-big-x86.qcow2,media=disk,if=virtio,index=0 -boot order=cd,once=d
```

This using qemu version 2.4.0 (old).

**Comment by cbrune** [comment]
At the end it boot in Debian OK.  Here are some hardware details:
```
debian login: onie                 
Password:                          
Linux debian 3.16.0-4-amd64 #1 SMP Debian 3.16.51-2 (2017-12-03) x86_64                                                                     

The programs included with the Debian GNU/Linux system are free software;                                                                   
the exact distribution terms for each program are described in the    
individual files in /usr/share/doc/*/copyright.                       

Debian GNU/Linux comes with ABSOLUTELY NO WARRANTY, to the extent     
permitted by applicable law.       
onie@debian:~$ uname -a            
Linux debian 3.16.0-4-amd64 #1 SMP Debian 3.16.51-2 (2017-12-03) x86_64 GNU/Linux                                                           
onie@debian:~$ sudo blkid
/dev/vda1: PARTLABEL="GRUB-BOOT" PARTUUID="f239fb30-130d-4bed-b188-f8e7dd4efcb5"
/dev/vda2: LABEL="ONIE-BOOT" UUID="69a8d8b8-c5f8-4e64-a6cb-bfe032d04172" TYPE="ext4" PTTYPE="dos" PARTLABEL="ONIE-BOOT" PARTUUID="a7969327-ce5d-42c2-9e58-bad3316b6edd"
/dev/vda3: UUID="1db0ecc0-1e1e-44ea-a817-66a6c3b311e3" TYPE="ext4" PARTUUID="1d203e23-1da6-4583-9de1-c584a54899bd"
/dev/vda4: UUID="7511e0a3-daa1-43e4-a52f-86fd2d0a8664" TYPE="swap" PARTUUID="9f5e8fa5-9d69-4cfa-af28-81004842b8fa"
```

**Comment by lockless** [comment]
thank you so much, it seems that my vm has no nic.

**Comment by lockless** [comment]
Thank you so much, it works now with your command. I guess the first my vm has no nic or it doesn't work.

**Comment by paulmenzel** [comment]
See [Installing Debian on a ONIE System](https://github.com/opencomputeproject/onie/tree/master/contrib/debian-iso) for reference.
