### ISSUE TITLE
An error occurred while compiling efivar.

### ISSUE THREAD

**Issue by fansss1116** [opencomputeproject/onie#725]
My compilation environment is centos7, and the following error occurs when efivar is compiled.

![default](https://user-images.githubusercontent.com/37991196/38231789-b7d2c8e0-3746-11e8-9f9e-d29e3a096cf6.PNG)

**Comment by fansss1116** [comment]
Gcc4.9 above is required.

**Comment by cbrune** [comment]
The ONIE build environment is only officially supported for Debian 9 build hosts.  However, a Debian 9 docker environment can also be used.  See #724

**Comment by cbrune** [comment]
@fansss1116 - try compiling with the docker container - https://github.com/opencomputeproject/onie/tree/master/contrib/build-env

**Comment by cbrune** [comment]
@fansss1116 - can we close this?
