### ISSUE TITLE
onie-syseeprom: the --set argument parser is case sensitive

### ISSUE THREAD

**Issue by cbrune** [opencomputeproject/onie#731]
This is a dumb one.

Setting an EEPROM TLV value using an *upper* case hex value fails, while using a *lower* case value works.

This fails:
```
onie-syseeprom --set 0x2B='Hardware Boxes R Us'
```

Instead the `2B` needs to be lower case: `2b`.  This works:

```
onie-syseeprom --set 0x2b='Hardware Boxes R Us'
```

**Comment by scott-emery** [comment]
Thank you for fixing this @cbrune! This has always annoyed me when (re)programming an EEPROM. I could never remember if the lowercase or uppercase hex digits were the ones accepted.

**Comment by cbrune** [comment]
Interestingly enough I discovered that *nginx* httpd works OK without brackets.  This is the httpd we use with the ONIE compatibility tests.  That is why this bug hadn't been seen.

I definitely see the problem when using *apache2* httpd.
