### ISSUE TITLE
machine type for DELL AS7512-32X

### ISSUE THREAD

**Issue by jimmymagemtek** [opencomputeproject/onie#764]
Is there any support for DELL AS7512-32X ?
Or any compatible existing type can be used ?

Any suggestion is appreciated.

**Comment by cbrune** [comment]
Are you sure it is DELL?  Accton has a machine with that part number:

 https://github.com/opencomputeproject/onie/tree/master/machine/accton/accton_as7512_32x

**Comment by jimmymagemtek** [comment]
Thank you!
