### ISSUE TITLE
ONIE build process missing packages

### ISSUE THREAD

**Issue by konstcranky** [opencomputeproject/onie#870]
Today i've tried to build onie 2019.02br
It seems some packages that ONIE uses is absent ? 

make: *** Waiting for unfinished jobs....
failed: Connection refused.
failed: Connection refused.
failed: Connection refused.
failed: Connection refused.
http://zlib.net/zlib-1.2.8.tar.gz:
2019-10-30 12:52:02 ERROR 404: Not Found.
wget: unable to resolve host address 'softlayer-dal.dl.sourceforge.net'
ERROR:  Unable to download zlib-1.2.8.tar.gz
make/zlib.make:39: recipe for target '/users/kostya/iss/onie/build/download/zlib-download' failed
make: *** [/users/kostya/iss/onie/build/download/zlib-download] Error 1
2019-10-30 12:52:02 URL:http://savannah-nongnu-org.ip-connect.vn.ua/dmidecode/dmidecode-3.1.tar.xz [61204/61204] -> "/users/kostya/iss/onie/build/download/dmidecode-3.1.tar.xz" [1]
dmidecode-3.1.tar.xz: OK
2019-10-30 12:52:04 URL:https://sourceware.org/git/?p=lvm2.git [35142] -> "/users/kostya/iss/onie/build/download/lvm2-2_02_105.tar.xz" [1]
lvm2-2_02_105.tar.xz: FAILED
sha1sum: WARNING: 1 computed checksum did NOT match
ERROR: Unable to verify sha1 for lvm2-2_02_105.tar.xz
make: *** [/users/kostya/iss/onie/build/download/lvm2-2_02_105-download] Error 1
make/lvm2.make:87: recipe for target '/users/kostya/iss/onie/build/download/lvm2-2_02_105-download' failed
2019-10-30 12:52:05 URL:https://matt.ucc.asn.au/dropbear/releases/dropbear-2016.74.tar.bz2 [1622234/1622234] -> "/users/kostya/iss/onie/build/download/dropbear-2016.74.tar.bz2" [1]
dropbear-2016.74.tar.bz2: OK

....

==== Getting upstream flashrom ====
failed: Connection refused.
https://web.daniel-baumann.ch/files/software/dosfstools/dosfstools-3.0.26.tar.xz:
2019-10-30 13:34:56 ERROR 404: Not Found.
ERROR:  Unable to download dosfstools-3.0.26.tar.xz
make: *** [/users/kostya/iss/onie/build/download/dosfstools-download] Error 1
make: *** Waiting for unfinished jobs....
make/dosfstools.make:41: recipe for target '/users/kostya/iss/onie/build/download/dosfstools-download' failed
2019-10-30 13:34:56 URL:https://mirrors.edge.kernel.org/pub/linux/kernel/people/tytso/e2fsprogs/v1.42.13/e2fsprogs-1.42.13.tar.xz [4802740/4802740] -> "/users/kostya/iss/onie/build/download/e2fsprogs-1.42.13.tar.xz" [1]
e2fsprogs-1.42.13.tar.xz: OK
http://download.flashrom.org/releases/flashrom-0.9.8.tar.bz2:
2019-10-30 13:34:57 ERROR 308: Permanent Redirect.
ERROR:  Unable to download flashrom-0.9.8.tar.bz2
make/flashrom.make:39: recipe for target '/users/kostya/iss/onie/build/download/flashrom-download' failed
make: *** [/users/kostya/iss/onie/build/download/flashrom-download] Error 1

Can you check please if this is my local problem?

**Comment by ehdoyle** [comment]
Thanks for posting this. I was just noticing this problem as well, so it saves me the trouble of making doubly sure it's not just me :)
What it looks like is that some of the URLs that ONIE downloads code from have changed or vanished. If you happen to already have an onie/build/downloads folder - don't delete it as the downloaded files are cached there. 
This, of course, does you no good if you're building from scratch.
I'm currently working on a patch to update these links, though even when fixed, I'm not sure that older builds will work. Going forward I've got some ideas on preventing this from happening again, but I'll focus on getting things up and running for now.

**Comment by ehdoyle** [comment]
Looks like http://mirror.opencompute.org/onie/ is back, so clean builds should work now. 
I'll be putting in a feature to look for a local system cache in /var/cache/onie/download.  As it works currently, ONIE saves these downloads under onie/build/download - but if you're starting from a clean checkout, that isn't present. but if you're using the same system for ONIE builds, you can copy the contents of onie/build/download into /var/cache/onie/download and it'll be around for future builds.
