### ISSUE TITLE
SFTP is more reliable, when will the SFTP function be added?

### ISSUE THREAD

**Issue by wcchen0519** [opencomputeproject/onie#990]
TFTP has no access authorization and authentication mechanism;
Secure File Transfer Protocol (SFTP) is a Secure File Transfer Protocol. SFTP uses encryption and decryption technologies to ensure the security of transferred files;

so SFTP is more reliable, when will the SFTP function be added?

**Comment by ehdoyle** [comment]
Hi - currently nobody is working on SFTP, but it would be great to have that added to ONIE.  As an open source project, ONIE has thrived and evolved through the contributions of the community, so we very much encourage the submission of pull requests to improve the code base.
Thanks!

**Comment by ehdoyle** [comment]
Closing out due to inactivity.
